### ISSUE TITLE
Incorrect return type for getClientRects in Range and Element modules

### ISSUE THREAD

**Issue by spocke** [tinymce/rescript-webapi#10]
All getClientRects assumes that the browser returns an array it's actually returning a DOMRectList.

Here is the relevant spec:
https://drafts.fxtf.org/geometry-1/#domrectlist

**Comment by TheSpyder** [comment]
https://github.com/tinymce/rescript-webapi/blob/784a1349b592f1ed810c178875bb01a16c759143/src/Webapi/Dom/Webapi__Dom__Element.re#L72
https://github.com/tinymce/rescript-webapi/blob/784a1349b592f1ed810c178875bb01a16c759143/src/Webapi/Dom/Webapi__Dom__Range.re#L42-L43

**Comment by TheSpyder** [comment]
@spocke the draft spec you linked has a note that `DOMRectList` is now considered legacy:

> DOMRectList only exists for compatibility with legacy Web content. When specifying a new API, DOMRectList must not be used. Use sequence<DOMRect> instead. [WEBIDL]
https://webidl.spec.whatwg.org/#idl-sequence

It's not entirely clear what `sequence` means regarding the API to access the items. I suspect it's the same as `NodeList`, which is what we were already expecting to use here.

**Comment by TheSpyder** [comment]
`Array.isArray(document.elementsFromPoint(0, 0))` returns true in the latest Safari, Chrome and Firefox. [The MDN spec also says Array](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementsFromPoint). I think we can close this.

**Comment by spocke** [comment]
Yeah I noticed that as well I'm guessing it some form of type that can be used as a generator in lazy sequences etc. I guess we could make a generic type for this that takes a type parameter. Like Sequence<DomRect> then have that being aliased as DomRectList but I guess it depends on how much plumbing we want to have inside the web api bindings. Having a generic type would make it easier to take that generic type and make it into our intent al lazy sequence type or if they ever add their own generator type directly to rescript.
