### ISSUE TITLE
elementFromPoint should return an option not an element

### ISSUE THREAD

**Issue by spocke** [tinymce/rescript-webapi#11]
The elementFromPoint may return null

See this description:
https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint

**Comment by TheSpyder** [comment]
https://github.com/tinymce/rescript-webapi/blob/784a1349b592f1ed810c178875bb01a16c759143/src/Webapi/Dom/Webapi__Dom__Document.re#L82
