### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Minnozz** [tinymce/rescript-webapi#19]
- Merge old README with the part currently added on top
- Convert syntax to ReScript
- Remove or update badges
- Point links to correct repo

**Comment by TheSpyder** [comment]
might be a good time to check whether bsdoc still works, and remove it if not

**Comment by TheSpyder** [comment]
We're nearly ready for this. I've just opened what should be the final PRs for 1.0.

Once I've merged those the final step will be converting our big internal codebase (94 files out of 600 in the project link to `bs-webapi`) to make sure the migration is easy - and probably using that experience to write up some migration docs at the same time.
