### ISSUE TITLE
Splitting Webapi__Dom__Window into WindowOrWorkerGlobalScope, WorkerGlobalScope

### ISSUE THREAD

**Issue by illusionalsagacity** [tinymce/rescript-webapi#21]
Relevant spec:
* https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope
* https://html.spec.whatwg.org/multipage/workers.html#workerglobalscope

Also relevant worker specs:
* https://html.spec.whatwg.org/multipage/workers.html#dedicatedworkerglobalscope
* https://html.spec.whatwg.org/multipage/workers.html#sharedworkerglobalscope
* https://w3c.github.io/ServiceWorker/#serviceworkerglobalscope

**Comment by TheSpyder** [comment]
We probably still want `Webapi.Dom.Window` to be a concept in the API, but it could also just `include` these two separate modules.
