### ISSUE TITLE
How to use window.scrollTo with options?

### ISSUE THREAD

**Issue by hellpirat** [tinymce/rescript-webapi#25]
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo - has options object with top, left, behavior - https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions

But our typings have only (float, float) params.

https://github.com/tinymce/rescript-webapi/blob/558c7d5a3eb533138114a1fc6fe7cdd9a2a33314/src/Webapi/Dom/Webapi__Dom__Window.res#L131

https://github.com/tinymce/rescript-webapi/blob/558c7d5a3eb533138114a1fc6fe7cdd9a2a33314/tests/Webapi/Dom/Webapi__Dom__Window__test.res#L73 -

**Comment by hellpirat** [comment]
Oh, I found https://github.com/tinymce/rescript-webapi/blob/558c7d5a3eb533138114a1fc6fe7cdd9a2a33314/src/Webapi/Dom/Webapi__Dom__Element.res#L132 these typings in Dom_Element, maybe we should add the same this typings to the window? :)

**Comment by hellpirat** [comment]
Solved this issue by Element.scrollToWithOptions but I am not sure if this right solution lol 

```
document
    ->documentElement
    ->Element.scrollToWithOptions({"top": 0.0, "left": 0.0, "behavior": "smooth"})
```

**Comment by TheSpyder** [comment]
I thought this might've been a product of varied browser support but no, it's just that the contribution was only made to element:
reasonml-community/bs-webapi-incubator#127

Feel free to PR it to window 🤷‍♂️

**Comment by TheSpyder** [comment]
In fact with ReScript's record-as-object capabilities maybe we create a `scrollToOptions` record type and use that. I'm planning to leverage records where possible and solidify all the breaking changes into 1.0.
