### ISSUE TITLE
localStorage bindings missing?

### ISSUE THREAD

**Issue by Minnozz** [tinymce/rescript-webapi#28]
https://github.com/tinymce/rescript-webapi/blob/72f023bba412720cf94dcbf700bc867ce7ce69c8/src/Webapi/Dom/Webapi__Dom__Window.res#L43

`Dom.Storage` does not seem to exist however. Or am I missing something?

**Comment by TheSpyder** [comment]
Because [ReScript already provides them](https://rescript-lang.org/docs/manual/latest/api/dom/storage2). We could add a module alias, I suppose, for discoverability.

**Comment by Minnozz** [comment]
Ah, I did not realize that `Dom` referred to ReScript's `Dom` instead of `Webapi.Dom`. Thanks!
