### ISSUE TITLE
Explicitly set all external values

### ISSUE THREAD

**Issue by TheSpyder** [tinymce/rescript-webapi#32]
I just ran a test compile with ReScript `10.0.0-dev.1` and there's a huge breaking change to this library. For some time, now, ReScript has had a warning (105) when externals are set to `= ""`. In the early days this was a convenient way to have the string automatically filled in with the external name; over time that mindset changed to "the string is required to avoid weird refactoring problems the compiler can't catch".

This project, having been created before that decision, uses `= ""` extensively. We just suppress the warning.

ReScript 10 appears to remove the warning in favour of a full on "invalid global name" error. We can address this early by turning off the suppression, it's just tedious - there are _844 externals that use `= ""` in this project_

To replicate, remove the `-105` from this line. I recommend using the vscode extension instead of a terminal build to avoid spam.
https://github.com/tinymce/rescript-webapi/blob/70af532eb04cea92ad737dd8264849e1d129394d/bsconfig.json#L20

It might be possible to use regex to solve this, I'm not sure. If not we might need to split up the work between multiple people.

**Comment by fhammerschmidt** [comment]
I think this should do the trick for single lines:
```
external (.+?):(.+?)= ""
```

Then, e.g. in VSCode, put the following into the replace field: 
```
external $1:$2= "$1"
```

I think the vast majority are one-liners anyway. Not sure if it is easier to come up with a more sophisticated regex or just to enable the warning and follow the compiler.

**Comment by Et7f3** [comment]
If you really need multi line support you can create a nodejs script that read a file as a big buffer do a regex with /gm and write back. And use `find . -name '*.res' -exec node script.js {} \;`to replace all file

**Comment by TheSpyder** [comment]
Thanks for the suggestions!

@yawaramin pointed out comby.dev has ReScript support so this should work:
`comby -diff 'external :[1]: :[2] = ""' 'external :[1]: :[2] = ":[1]"' Webapi__File.res`

**Comment by TheSpyder** [comment]
Note, keep an eye on these two lines, they must remain `= ""`. I'm not sure what ReScript 10 does with them; if it fails I'll log a bug.
https://github.com/tinymce/rescript-webapi/blob/6ba6e48be26a050d4be42d69a7721a188aa45925/src/Webapi/Dom/Webapi__Dom__DomStringMap.res#L5-L6

**Comment by Et7f3** [comment]
For this we have two options negative lookbehind or just do another regex for lines with theses attributes

**Comment by TheSpyder** [comment]
There's only the two, as far as I can find, I think they can be reverted manually.

I should have time to look at this tomorrow. There isn't a huge rush on v10 support but I feel like getting ahead of these problems will be better than rushing to fix them later.

**Comment by TheSpyder** [comment]
Comby was _brilliant_. The command from @yawaramin picked up almost everything, even simple multi-line externals, there were only a handful of big multi-line externals I had to fix manually.

> Note, keep an eye on these two lines, they must remain `= ""`. I'm not sure what ReScript 10 does with them; if it fails I'll log a bug.

Comby updated them and they became a compile error. So they clearly need to remain placeholders.
