### ISSUE TITLE
WebSocket may have misleading typing

### ISSUE THREAD

**Issue by ValdemarGr** [tinymce/rescript-webapi#44]
We have just started using the merged WebSocket implementation, thank you for the work :)
We noticed that the type of `messageEvent` may be misleading;

The docs state that:
https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/data
"The data sent by the message emitter; this can be any data type."

But the implementation gives the caller the promise of a `Js.Json.t`.
https://github.com/tinymce/rescript-webapi/blob/b138ae2982d24193473e01929251871ea2d4ba65/src/Webapi/Webapi__WebSocket.resi#L54-L58

(https://html.spec.whatwg.org/multipage/web-sockets.html)
For WebSockets, it seems that the data type should be something like
```rescript
type data =
  | ArrayBuffer(array_buffer)
  | Blob(Webapi__Blob.t)
  | String(string)
```

**Comment by spocke** [comment]
There are convert functions for it here https://github.com/tinymce/rescript-webapi/blob/b138ae2982d24193473e01929251871ea2d4ba65/src/Webapi/Webapi__WebSocket.resi#L91 maybe it should be an opaque type in the message record or we add a little decoder that converts it to a variant.

**Comment by ValdemarGr** [comment]
Yes, I see now.
Thank you for the explanation.

> maybe it should be an opaque type in the message record or we add a little decoder that converts it to a variant.

I think this is a good idea, it was not entirely trivial to find the root cause with `Js.Json.t` as the type :)

**Comment by TheSpyder** [comment]
I’d rather not add wrappers by making it a variant. My aim was to make certain patterns easier by having data on the record type but I think got carried away. I either need to:
- separate the message event type into a new module, so the locality of functions make the options for data use more clear
- remove data from the record type and rearrange the module to put the “message as” methods next to the record type.

should I rename the methods as well? Perhaps `messageDataAsBinary`?
