### ISSUE TITLE
Add bindings to DataTransfer

### ISSUE THREAD

**Issue by spocke** [tinymce/rescript-webapi#50]
We should have bindings for DataTransfer.

Relevant spec: https://html.spec.whatwg.org/multipage/dnd.html#the-datatransfer-interface

**Comment by TheSpyder** [comment]
This was PR'd to the bs-webapi repo, I forgot to port it over
reasonml-community/bs-webapi-incubator#208 and reasonml-community/bs-webapi-incubator#209

**Comment by spocke** [comment]
Looking at that PR it was less extensive. I think I covered the full spec.
