### ISSUE TITLE
Add bindings to File constructor

### ISSUE THREAD

**Issue by spocke** [tinymce/rescript-webapi#52]
Relevant spec: https://w3c.github.io/FileAPI/#dom-file-file

**Comment by TheSpyder** [comment]
I thought we had some way to do this already 🤔 I'll put it into the 1.0 release but if we don't get to it that's fine

**Comment by spocke** [comment]
> I thought we had some way to do this already 🤔 I'll put it into the 1.0 release but if we don't get to it that's fine

We have a hacky binding for strings only in our internal bindings. Maybe That this the one you are thinking of.

**Comment by spocke** [comment]
Started a branch here: https://github.com/tinymce/rescript-webapi/compare/file-constructor
Not sure how to handle all the typed array variants.

https://rescript-lang.org/docs/manual/latest/api/js/typed-array

In the spec they are one single type:
https://webidl.spec.whatwg.org/#ArrayBufferView

Maybe we could do some form of typedArrayLike thing here not sure or at least have them in their own module.

**Comment by spocke** [comment]
I just added functions from typed array variants directly to blobParts I think we would want that anyway even if we had a generic ArrayBufferView type.
