### ISSUE TITLE
Add bindings to input events like beforeinput

### ISSUE THREAD

**Issue by spocke** [tinymce/rescript-webapi#53]
Includes beforeinput and input event.

Relevant spec: https://www.w3.org/TR/input-events-2/

**Comment by TheSpyder** [comment]
Most of the bindings already exist:
https://github.com/tinymce/rescript-webapi/blob/18d9d553201d575fa8e194d3370298b556b28747/src/Webapi/Dom/Webapi__Dom__EventTarget.res#L680-L685

We just needed to add bindings for `inputType` and `dataTransfer` on the resulting input event.

**Comment by TheSpyder** [comment]
Released as 0.5.0
