### ISSUE TITLE
Fix incorrect bindings for mutation record

### ISSUE THREAD

**Issue by spocke** [tinymce/rescript-webapi#54]
These are incorrect:
```
@get @return(nullable) external pnextSibling: t => option<Dom.node> = "pnextSibling"
@get external attributeName: t => string = "attributeName"
```

Should be changed to this:
```
@get @return(nullable)
external nextSibling: Tiny.Dom.MutationRecord.t => option<Tiny.Dom.Node.t> = "nextSibling"
@get @return(nullable)
external attributeName: Tiny.Dom.MutationRecord.t => option<string> = "attributeName"
```

Looks like there is other things that is nullable so compare with the spec.

Relevant spec: https://dom.spec.whatwg.org/#interface-mutationrecord

**Comment by TheSpyder** [comment]
This was inherited from bs-webapi, if it's been broken that long it's a safe change to include in 1.0
