### ISSUE TITLE
Fix type of HtmlElement.ofElement

### ISSUE THREAD

**Issue by TheSpyder** [tinymce/rescript-webapi#60]
I totally forgot we inherited this bug:
https://github.com/tinymce/rescript-webapi/blob/18d9d553201d575fa8e194d3370298b556b28747/src/Webapi/Dom/Webapi__Dom__HtmlElement.res#L8

The type should be `let ofElement: Dom.element => option(t_htmlElement)` but currently it's `Dom.element => option<Dom.htmlElement>`. This concrete type breaks modules that inherit from `HtmlElement`, e.g. reasonml-community/bs-webapi-incubator#205

This happened when `bs-webapi` was changed to use safer `instanceof` checks rather than the previous way of checking if a HTML attribute existed:
https://github.com/reasonml-community/bs-webapi-incubator/pull/182/files?file-filters%5B%5D=.re#diff-f6590c311eac02db4a8591dfe7b1a4c232207269ed2d71105f8407ad4c5ba34dL13-R4

There have been a number of bugs with this change - we perhaps need to rethink it.

**Comment by TheSpyder** [comment]
Ah, damn. I had a version that included a fallback but then I saw `prototype.constructor` has worked since ie8.

This is a similar change that was made in TinyMCE recently - turns out there was an edge case where creating an element and attaching it in an iframe breaks all instanceof checks.

**Comment by spocke** [comment]
But wouldn't the element.defaultView.HTMLElement fix that case?

**Comment by TheSpyder** [comment]
There’s a TinyMCE test that failed with the old code. I’ll post the link when I get to my desk.

**Comment by TheSpyder** [comment]
https://github.com/tinymce/tinymce/blob/715f59c3a8b2bb35d2a158902a1b245987185b17/modules/sand/src/test/ts/browser/HtmlElementTest.ts#L34-L51
