### ISSUE TITLE
The version  in the npm registry is 1 year old

### ISSUE THREAD

**Issue by greyblake** [tinymce/rescript-webapi#82]
Hi, thank you for the great bindings!

Currently the README provides the following installation instructions:
```
npm install bs-webapi
```

But the last version of [bs-webapi](https://www.npmjs.com/package/bs-webapi) was published a year ago.
Since that some APIs changed. Would you consider publishing a new version to npm?

Thank you.

**Comment by TheSpyder** [comment]
Yes, the readme states near the top
> This project is in the process of being forked; what follows is the original readme.

There's a first pass at a readme update in #80.

You now want `npm install rescript-webapi` - sorry for the confusion.
