### ISSUE TITLE
missing HtmlInputElement.t converter

### ISSUE THREAD

**Issue by mattdamon108** [tinymce/rescript-webapi#96]
Hi,

I have to getElementById of the input element and need to set the value of it. But I can't find the converter function from Dom.Element -> Dom.HtmlInputElement.

```rescript
let _ = (document |> Document.getElementById("site_cd"))
            ->Option.flatMap(HtmlInputElement.ofElement)
            // Dom.HtmlInputElement.ofElement: Webapi__Dom__Element.t => option<Dom.htmlElement>
            // why not Webapi__Dom__Element.t => option<Dom.htmlInputElement> ??
            ->Option.map(e => e->HtmlInputElement.setValue)
```

**Comment by TheSpyder** [comment]
Which version are you using? The type of `HtmlInputElement.ofElement` has been wrong for a while, but a recent release should have fixed that up.

**Comment by mattdamon108** [comment]
Oh! my bad. This came from one of my projects which is still using `bs-webapi`. I've checked the current `rescript-webapi` resolves this. 👍
